import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Wireless Earbuds Pro",
        description: "High-quality wireless earbuds with noise cancellation.",
        price: 350,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Devices",
        createdAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "Smart Fitness Watch",
        description: "Track your fitness goals with this advanced smartwatch.",
        price: 450,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Devices",
        createdAt: new Date().toISOString(),
    },
    {
        id: "3",
        name: "Portable Power Bank 20000mAh",
        description: "Fast charging power bank for all your devices.",
        price: 180,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Accessories",
        createdAt: new Date().toISOString(),
    },
    {
        id: "4",
        name: "Leather Messenger Bag",
        description: "Premium leather bag for work and travel.",
        price: 550,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Bags",
        createdAt: new Date().toISOString(),
    },
    {
        id: "5",
        name: "Running Sneakers",
        description: "Lightweight and comfortable shoes for your daily run.",
        price: 320,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Shoes",
        createdAt: new Date().toISOString(),
    },
    {
        id: "6",
        name: "Cotton T-Shirt Pack",
        description: "Soft and breathable cotton t-shirts (Pack of 3).",
        price: 150,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Clothing",
        createdAt: new Date().toISOString(),
    },
    {
        id: "7",
        name: "Smartphone Stand",
        description: "Adjustable stand for your smartphone or tablet.",
        price: 45,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Accessories",
        createdAt: new Date().toISOString(),
    },
    {
        id: "8",
        name: "Classic Denim Jacket",
        description: "Timeless denim jacket for a casual look.",
        price: 280,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Clothing",
        createdAt: new Date().toISOString(),
    }
];
