import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Premium Cotton Socks",
        description: "Soft and breathable premium cotton socks.",
        price: 35,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Socks",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "2",
        name: "Casual Shorts",
        description: "Comfortable cotton shorts for casual wear.",
        price: 85,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Shorts",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "3",
        name: "Slim Fit Trousers",
        description: "Elegant slim fit trousers for office and formal wear.",
        price: 180,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Trousers",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "4",
        name: "Leather Messenger Bag",
        description: "Premium leather bag for work and travel.",
        price: 550,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Bags",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "5",
        name: "Nocta Running Sneakers",
        description: "Lightweight and comfortable shoes for your daily run.",
        price: 320,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Sneakers",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "6",
        name: "Graphic T-Shirt",
        description: "Stylish graphic t-shirt for everyday wear.",
        price: 120,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Tops/Shirts",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "7",
        name: "Classic Aviator Glasses",
        description: "Timeless aviator glasses with UV protection.",
        price: 150,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Glasses",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    },
    {
        id: "8",
        name: "Cotton Boxers Pack",
        description: "Soft and breathable cotton boxers (Pack of 3).",
        price: 95,
        currency: "GHS",
        images: ["/placeholder.svg"],
        status: "active",
        category: "Briefs/Boxers",
        isEnabled: true,
        createdAt: new Date().toISOString(),
    }
];
